server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/**
#            - name: My
#              args:
#                user: zhx
            - My=zhx
#            - Method=POST,GET
#            - RemoteAddr=192.168.0.1/24
#            - Query=username, \d+
#            - Host=**.zhx.com
#            - Header=Zhx-Id, \d+
#            - Cookie=zhx,zyf
#            - After=2024-08-09T17:36:18.042997900+08:00[Asia/Shanghai]
#            - Before=2024-08-09T17:38:18.042997900+08:00[Asia/Shanghai]
#            - Between=2024-08-09T17:40:00.042997900+08:00[Asia/Shanghai],2024-08-09T17:40:20.042997900+08:00[Asia/Shanghai]
        - id: pay_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gatewayInfo/**
        - id: pay_routh3
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/filter/**
#            - Path=/gateway/filter/**
#            - Path=/ZHX/ZYF/{param}
          filters:
            - My=zhx
#            - RedirectTo=302, http://www.baidu.com/  #重定向
#            - SetPath=/pay/gateway/{param} #{segment}表示占位符  {}里写啥都行但要保持上下一致
#            - PrefixPath=/pay #前缀

#            - AddResponseHeader=X-response-zhx,zhx #新增请求参数
#            - SetResponseHeader=Date,2099-9-9  #更新Date
#            - RemoveResponseHeader=Content-Type #删除

#            - AddRequestParameter=userId,999 #新增请求参数
#            - RemoveRequestParameter=username #移除请求头参数

#            - SetRequestHeader=sec-fetch-mode,ZHXZYF  #更新请求头
#            - RemoveRequestHeader=sec-fetch-site #移除请求头
#            - AddRequestHeader=X-request-zhx,zhx # 增加请求头
#            - AddRequestHeader=X-request-zyf,zyf